apiVersion: v1
kind: Namespace
metadata:
  name: curso-_USERNAME_

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-_USERNAME_-deployment
  namespace: curso-_USERNAME_
spec:
  selector:
    matchLabels:
      app: webserver-_USERNAME_
  template:
    metadata:
      labels:
        app: webserver-_USERNAME_
    spec:
      containers:
      - name: webserver-_USERNAME_
        image: nginx
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "512Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: webserver-_USERNAME_-service
  namespace: curso-_USERNAME_
spec:
  type: NodePort
  selector:
    app: webserver-_USERNAME_
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000

---

# apiVersion: networking.k8s.io/v1
# kind: IngressClass
# metadata:
#   name: gcp-lb-_USERNAME_
# spec:
#   controller: k8s.io/ingress-gce
#   parameters:
#     apiGroup: k8s.example.com
#     kind: IngressParameters
#     name: external-lb

# ---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-_USERNAME_
  annotations: 
    kubernetes.io/ingress.class: "gce"
  namespace: curso-_USERNAME_
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: webserver-_USERNAME_-service
            port:
              number: 80
              