apiVersion: v1
kind: Namespace
metadata:
  name: curso-_USERNAME_

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-course
  namespace: curso-_USERNAME_
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce