apiVersion: v1
kind: Namespace
metadata:
  name: curso-_USERNAME_

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-_USERNAME_-deployment
  namespace: curso-_USERNAME_
spec:
  selector:
    matchLabels:
      app: webserver-_USERNAME_
  template:
    metadata:
      labels:
        app: webserver-_USERNAME_
    spec:
      containers:
      - name: webserver-_USERNAME_
        image: gcr.io/google-samples/hello-app:1.0
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "512Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: webserver-_USERNAME_-service
  namespace: curso-_USERNAME_
spec:
  type: NodePort
  selector:
    app: webserver-_USERNAME_
  ports:
  - name: expose-port
    protocol: TCP
    targetPort: 8080
    port: 30000

---

# apiVersion: networking.k8s.io/v1
# kind: IngressClass
# metadata:
#   name: gcp-lb-_USERNAME_
# spec:
#   controller: k8s.io/ingress-gce
#   parameters:
#     apiGroup: k8s.example.com
#     kind: IngressParameters
#     name: external-lb

# ---

apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-course-cert
  namespace: curso-_USERNAME_
spec:
  domains:
    - k8scurso.veram.xyz

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-_USERNAME_
  annotations:
    kubernetes.io/ingress.global-static-ip-name: course-global-ip
    networking.gke.io/managed-certificates: managed-course-cert
    kubernetes.io/ingress.class: "gce"
  namespace: curso-_USERNAME_
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: webserver-_USERNAME_-service
            port:
              name: expose-port
              